### ISSUE TITLE
Update API4

### ISSUE THREAD

**Issue by mukeenanyafiq** [matcracker/ServerTools#10]
Please update it to API4 because this plugin is so awesome.

If you're busy, let us make API4 Pull Request Plugin.
It's not appearing in [Poggit-CI](https://poggit.pmmp.io/ci/matcracker/ServerTools)

**Comment by matcracker** [comment]
You can already submit a PR for PM4 update. If it is ok, it will be merged in the master branch.

**Comment by mukeenanyafiq** [comment]
Nice. Thanks
I'm making this issue because I wanna check my PR API4 problem
