### ISSUE TITLE
Restart Issue

### ISSUE THREAD

**Issue by lixsady** [matcracker/ServerTools#12]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. Pressed restart button in game
2. the plugin reopened the wrong start file

### OS and versions

* ServerTools:

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by matcracker** [comment]
The plugin has a configuration file which allows to indicates the file to execute.
