### ISSUE TITLE
ftp.php file location

### ISSUE THREAD

**Issue by glitchedmc** [matcracker/ServerTools#2]
Where do i find the necassary files for cloning a server. Im trying to use your plugin but i dont know where to get the ftp.php file or any of the other...

**Comment by matcracker** [comment]
What do you mean? Did you want to say the ftp extension?

**Comment by matcracker** [comment]
I close the issue until more information are provided.

**Comment by glitchedmc** [comment]
Im trying to clone my server but on the plugin info u say i need an ftp
extension file or something. Its was an ftp.php or sonething like that.
Where do i download this required file so i can clone my server

**Comment by matcracker** [comment]
Just search on Google the instructions because it depends on your OS. https://www.php.net/manual/en/ftp.installation.php

**Comment by glitchedmc** [comment]
Ok thnk u
