### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by AIPTU** [matcracker/ServerTools#7]
### Issue description

- Expected result: Player as Operator can use servertools
- Actual result: Player as Operator can not use servertools

### Steps to reproduce the issue
1. Install ServerTools
2. Run command /servertools as Operator
3. Open the UI and select a button 

### OS and versions
* ServerTools: Latest Poggit Release
* PocketMine-MP: 3.21.0
* PHP: 7.4.20
* Server OS: Linux

**Comment by matcracker** [comment]
There is a reason why OP players does not have access to some plugin function. It's specifically wrote in the FAQ of the README file. If you have any doubts about, let me know :)

**Comment by AIPTU** [comment]
It's a little troublesome lol

**Comment by matcracker** [comment]
I could add an option in the config where an operator can bypass all the permissions.
